services:
  app:
    build: .
    container_name: code-form-app
    ports:
      - '3000:3000'
    environment:
      - DB_NAME=code-form
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=5432
      - DB_HOST=db
      - JWT_SECRET=ASIJAJ9SJAIJSAJSIAJISJAISJAI23989A8S9AS8A9S
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db
    networks:
      - code-form-network

  nginx:
    image: nginx:latest
    container_name: nginx-code-form
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - code-form-network

  db:
    image: postgres:14
    container_name: code-form-dev
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_DB=code-form
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - code-form-network

networks:
  code-form-network:
    driver: bridge

volumes:
  pgdata: